spring.application.name=loanlens

# PostgreSQL - Neon
spring.datasource.url=jdbc:postgresql://ep-muddy-darkness-aoceaco9-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jdMt9VFiU0AN
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis - Upstash
spring.data.redis.host=suitable-coyote-119896.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAdRYAAIgcDIyZWNiZDhlNGE3MzY0MmU0YmVjZTVkNmJmZDg2NWM3NQ
spring.data.redis.ssl.enabled=true

# Server
server.port=8080

